language: r
r:
- release
- devel
os:
- linux
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages

warnings_are_errors: true

notifications:
  email:
    on_success: never
on_failure: change
